### ISSUE TITLE
buble import error

### ISSUE THREAD

**Issue by btakita** [riot/compiler#100]
```
<custom-tag>
  <script type="buble">
    import 'my-file'
  </script>
</custom-tag>
```
Results in:
`import is not supported` error

If you pass in the options `{transforms: {modules: false}}` into the Buble compiler, the issue does not occur. See https://gitlab.com/Rich-Harris/buble/blob/master/src/program/types/ImportDeclaration.js

Here is a monkey-patch I used to fix the issue in my project.
```
const parsers__riot = require('riot-compiler/lib/parsers')
    , {js} = parsers__riot
    , {buble} = js
js['javascript'] = js['buble'] = js['ecmascript-6'] = _loadParser
function _loadParser(p1, p2, p3, p4) {
  return buble(p1, Object.assign({transforms: {modules: false}}, p2), p3, p4)
}
```

**Comment by aMarCruz** [comment]
@btakita , `modules: false` is already used in the parser:

See https://github.com/riot/compiler/blob/master/lib/parsers/buble.js#L15

**Comment by GianlucaGuarini** [comment]
@aMarCruz I guess it should be `{ transforms: { modules: false } }`

**Comment by aMarCruz** [comment]
oh god, @GianlucaGuarini you're right, `modules` is a `transforms` property.
