### ISSUE TITLE
Auto inject scripts/styles into jade, html

### ISSUE THREAD

**Issue by osv** [riot/compiler#101]
## Motivation

I use emacs which is not support coffeescript + jade together well, but I love riot and would like to import coffeescript into html/pug in some fancy and easier way.

How can it be done with current riot compiler
```html
<my-component>
  <script>
    import {coffeeCode} from  './my-component.coffee'
    // ...somehow use coffeeCode to initialize `this` in properway.
  </script>
</my-component>
```
which produce code like
```js
import coffeeCode from  './my-component.coffee'
riot.tag2('my-component', '', '', '', function(opts) {
});
```
Cons:
- I need to configure rollup/webpack, etc to understand how to import coffeescript.
- I need write init code - add `import`, `exports` and init `this` context with imported stuff. **This code make only noise** for me

## What I propose.

Add optional param to compiler, let say `autoInject`. Now, when you have next files:

- my-component.tag
- my-component.coffee
- my-component.js
- my-component.ls
- my-component.css

Riot compiler with option `autoInject: ['js','ls', 'coffee', 'css']` (order is important) inject into my-component.html scripts tag:
```html
...
    <style>
        // content of my-component.css
    </style
    <script>
      //content of my-component.js
    </script>
    <script type="livescript">
      // content of my-component.ls
    </script>
    <script type="coffeescript">
      // content of my-component.coffee
    </script>
</my-component>
```

Simple, yes?

Pros:
- No import bullshit. We have **file name convention**, each files with same tag (html) name is related to this component, we don't expect that some of file of component will be imported by other component/service/etc. You still free to use other related name, for example, "my-component.**service**.js" to specify shared importable file that cannot be injected but indicate that this is shared file
- Again, no `exports` bullshit. You can copy paste code from script to external file or from external file to script tag without any modification. Code in external file my-component.coffee is still simple to read
```coffeee
@onClick = (event) => #...
```
- No need to configure rollup/webpack if you use coffescript for **component only**.

Cons:
- If you want to require code for example for testing it you will fail. Looks like you need to write wrapper and load/eval manually. Not a big problem
- sourcemap. Additional sourcemap work is require :(
- There might be code in different places, maybe not good.
- Maybe you need to write additional exclusion in your browserify, rollup, webpack plugins which rebase/concat files that is not implicitly imported. For example plugin can concat  all `css` files. Not a problem because many plugins allow you set exclude pattern, good name convention should help.

-----
I can spend some time on this feature if you are interesting. Basic code should be really trivial if don't think about sourcemap. What do you think?

**Comment by osv** [comment]
I just found that it not possible to do so in compiler level because `compiler.compile` can take string. This improvement can be valid for riot-cli, rollup plugin, etc

**Comment by GianlucaGuarini** [comment]
The new compiler v4.0.0 is 100% module syntax compatible. You will be able to import javascript, css, scss using any javascript bundler like `webpack` or `rollup`.
