### ISSUE TITLE
riot-tmpl dependency

### ISSUE THREAD

**Issue by amenadiel** [riot/compiler#104]
I see that `dist/es6.compiler.js` starts with
```js
import { brackets } from 'riot-tmpl';
```

however, there's no `riot-tmpl` package listed anywhere.

**Comment by amenadiel** [comment]
It seems compiler has always been considered as part of main riot, which has tmpl as a dependency. This problem only arose when trying to use the compiler as a standalone.

By the way, adding tmpl as a de dependency to the compiler repo and running rollup mades a fully functional es6.compiler.js, which is ideal to use for my systemjs-riot plugin.

**Comment by GianlucaGuarini** [comment]
I think we can add `riot-tmpl` as a `peerDependency` in the `package.json` file
