### ISSUE TITLE
Riot-compiler dependencies are broken on NPM

### ISSUE THREAD

**Issue by klen** [riot/compiler#105]
Hello,

I was trying to figure out why riot-compiler uses coffee-script@1.12.7 instead coffeescript@2. The riot-compiler trying to import coffee-script before coffeescript but it's not a problem while you don't have installed coffee-script. I don't have coffee-script inside my dependencies, but it's somehow always installed. I've found when you install riot (riot-compiler) it installs coffee-script@1.12.7 (and a lot of other unused libraries). For now, for example, there is no ability to use coffeescript2 in your tags.

After some investigations I've found that `riot-compiler` dependencies on NPM are really different from the repository: https://www.npmjs.com/package/riot-compiler

They contain for example `coffee-script, livescript, sass, pug and etc`. Looks like somebody uploaded the package with a changed package.json file. It happens when you make `npm install`in the repository, it changes package.json (because of scripts I suppose).

**Solution**: Rebuild and reupload the package on NPM with correct package.json file.

**Comment by GianlucaGuarini** [comment]
thank you your patch fixed the issue

**Comment by klen** [comment]
@GianlucaGuarini  Great! Thank you!
