### ISSUE TITLE
Source maps in browser

### ISSUE THREAD

**Issue by towerofnix** [riot/compiler#108]
I'm developing an app which is hosted on GitHub pages. It simply uses the usual `riot.mount`/`<script src="some.cdn/riot.min.js">` combination so that publishing is easy, and we don't have to rebuild the site whenever we want to push a change.

Unfortunately, I've ran into an issue with Riot: its stack traces are *really, really bad.* I'm talking *this* bad:

![riot+compiler.min.js:2, riot+compiler.min.js:2, riot+compiler.min.js:2, riot+compiler.min.js:2...](https://user-images.githubusercontent.com/9948030/34071163-21dbc066-e26a-11e7-83be-d2810e3dcb86.png)

Apparently there's now an experimental way to use source maps with Riot, per https://github.com/riot/compiler/issues/56#issuecomment-350485291. But this doesn't explain how to use source maps when compiling in the browser. I read [the only documentation on Riot sourcemaps I could find](https://github.com/riot/compiler/tree/master/doc#sourcemaps-experimental) and it appears to be that sourcemaps only work in node. Is there any way for me to build and practically use sourcemaps in the browser, and if not, is there any plan for this?

**Comment by GianlucaGuarini** [comment]
how do you compile your riot tags?

**Comment by GianlucaGuarini** [comment]
source maps of course are not supported for in browser compilation. In your case the error seems to be really simple you have a component called `<message>` having the expression `revisions[0].text` undefined. What do you need to know more than that?

**Comment by towerofnix** [comment]
Sure, in my case I could solve it. I did, in fact - it was a one line change because the PR implementing this was using an old, slightly different version of my API. But what if the error were `text is undefined`? There are likely to be *many* variables named `text` in my program, so I can't just do a ^-F for `text`.

I compile them with `riot+compiler`:

```js
<script src='https://cdn.jsdelivr.net/combine/npm/riot@3/riot+compiler.min.js,npm/riotcontrol@0.0.3,npm/katex@0.9.0-alpha2,npm/mousetrap@1.6.1/mousetrap.min.js'></script>

<script src='/tags/modal.tag' type='riot/tag'></script>
<script src='/tags/form-input.tag' type='riot/tag'></script>
...

<script>
  // Compile Riot tags and mount them to the view
  riot.compile(() => {
    const tags = riot.mount('*')
  })
</script>
```

**Comment by GianlucaGuarini** [comment]
1. riot at moment even without sourcemaps will tell you the name of the component and the expression failing, there will be never errors like `text is undefined`
2. sourcemaps can be already generated using https://github.com/riot/rollup-plugin-riot, I will port sourcemaps on the whole riot ecosystem asap

**Comment by towerofnix** [comment]
>riot at moment even without sourcemaps will tell you the name of the component and the expression failing, there will be never errors like text is undefined

Cool - I didn't notice that. Is there any mention of how those error messages are displayed in the documentation? I didn't see anything in a ^-F for "error", and the two messages logged after the error are relatively cryptic (e.g. just "`<message-group>`", not "`above error occurred in `<message-group>`", and then a mysterious object which I don't even know the purpose of logged). Of course this is a case of I, the user of a library, not knowing everything the developer knows, and there being a lack of information regarding it.

> there will be never errors like `text is undefined`

Sure there will be? Here's the basic code for my hypothetical `<messages>` tag:

```
<messages>
  <script>
    const titel = 'hello'
    document.title = title
  </script>
</app>
```

This, of course, has an error: `title` is a reference error, because I defined `const titel`, not `const title`. And here's the error Riot shows me:

![Stack trace](https://user-images.githubusercontent.com/9948030/34071664-a0a97814-e271-11e7-950f-004f7484c698.png)

The best I get is that the error is *somewhere* in `messages.tag.js`. The line/column indicator (`/tags/messages.tag.js:3:5` isn't helpful, by the way: it points here:

```js
    const titel = 'hello'
....^
```

And obviously the error is here:

```js
    document.title = title
.....................^
```

When the error is in the actual "tag code" (e.g. `<foo kar={ baz.bar.bah }>`) instead of a `<script>`, I do get slightly more information, but as I said above it's not very clear.

>source maps of course are not supported for in browser compilation.

Why not? I'm somewhat new to the world of compilation so do excuse me if this is a silly question, but.. couldn't you compile the sourcemaps such that they're inline with the resulting JS? (I've read that the main reason inline sourcemaps are a bad idea is because they'd use toooons of data, but since all compilation with riot.compile in the browser is done in memory, that wouldn't be a problem.)

**Comment by GianlucaGuarini** [comment]
The new compiler v4.0.0 generates really precise source maps. We provide just a basic source maps support for the runtime compilation, please compile your tags via node (webpack, rollup, prepack, riot cli) to enable this feature.
