### ISSUE TITLE
Fallback to babel-core. You might want to upgrade to @babel/core soon.

### ISSUE THREAD

**Issue by B1nke** [riot/compiler#109]
This console message caused a big pain the last few days when all the builds started to fail. Raised an issue with the babel team as I thought it was from them:
https://github.com/babel/babel/issues/8014

I managed to get it to build now by using version ~3.4.0

**Comment by GianlucaGuarini** [comment]
could you please replicate the issue in a small repo?
> This console message caused a big pain the last few days when all the builds started to fail.

This sentence doesn't help me that much. Apparently you are using simultaneously 2 babel versions in the same project.

**Comment by sambrenner** [comment]
Seeing this as well, though it's not breaking anything. I've recreated the issue in a repo here: https://github.com/sambrenner/riot-babel-core. Clone, `npm install`, `node_modules/.bin/riot --type es6 test.tag`. Hope this helps.

**Comment by GianlucaGuarini** [comment]
I was able your repo @sambrenner thank you. I don't see any bug or issue here.

**Comment by surmind** [comment]
@sambrenner 
`npm install @babel/core` solve the problem.
It seems babel-core is babel 6, @babel/core is babel 7 (in beta).

As the code shows,  @bable/core or warning, choose one.

https://github.com/riot/compiler/blob/0a0d568a5ca7d2512ded14b982ddcda80edc846d/lib/parsers/es6.js#L12-L19
