### ISSUE TITLE
Indentation issue

### ISSUE THREAD

**Issue by amitguptagwl** [riot/compiler#110]
I've found a weird issue. When I write a tag like this, compiler works fine;

```html
<riot-rect>
        <rect ref="rect" onmousedown={hold}   />

 </riot-rect>
```

But in case of this

```html
<riot-rect>
        <rect ref="rect" onmousedown={hold}   />

    </riot-rect>
```
compiler output is
```js
<riot-rect>
riot.tag2('rect', '', '', 'ref="rect" onmousedown="{hold}"', function(opts) {
});

    </riot-rect>
```

**Comment by GianlucaGuarini** [comment]
This is not an issue it's how the current compiler works by design https://github.com/riot/compiler/blob/master/doc/guide.md#indentation
