### ISSUE TITLE
Parse error when use stylus as css preprocessor

### ISSUE THREAD

**Issue by gaconkzk** [riot/compiler#127]
Setting up a riot project using rollup and stylus css preprocessor, seem the compiler put wrong css code into registerPreprocessor function.

Repository for error reproduce: https://github.com/gaconkzk/fliesml
(https://github.com/gaconkzk/fliesml/commit/4e904c7d09376f2dcc598815b98fe3ac1ba83a8c)

Error:
![error-fliesml](https://user-images.githubusercontent.com/1164543/63411412-aef78c80-c41f-11e9-833c-d46c0e9a651a.png)

Expect behavior: The parameter code in registerPreprocessor should have \n in them
Actual: All `\n` characters was remove so the `stylus` parser can't parse.

**Comment by GianlucaGuarini** [comment]
@gaconkzk you are absolutely right, that's a bug. The css output shouldn't be compressed before going through the compilers. I will need to patch these lines and it should be a trivial fix https://github.com/riot/compiler/blob/master/src/generators/css/index.js#L102-L103

**Comment by gaconkzk** [comment]
It worked. Thanks.
