### ISSUE TITLE
Asynchronous preprocessor

### ISSUE THREAD

**Issue by RedKenrok** [riot/compiler#132]
I want to use PostCSS as a pre processor for the styling in my components/ unfortunately PostCSS is unable to run synchronously. Since the preprocessor is called synchronous there is nothing to return until PostCSS is resolved. Can a feature be added to give the compiler the ability to call this asynchronously.

**Comment by GianlucaGuarini** [comment]
PostCSS can [compile synchronously](https://www.npmjs.com/package/postcss#browser) use `postcss.sync`. 

The Riot.js compiler is sync by default because otherwise it would be not possible to include and compile Riot.js components in node for SSR:

```js
import App from 'app.riot' // this should be sync
```

**Comment by RedKenrok** [comment]
Thank you for quick response.

`postcss.sync` is a `postcss-js` method only and is used for CSS in JS. This will not provide you with right results as it returns an object which each character indexed in the object. What will work is the following:

```JS
// Import Riot compiler.
import { registerPreprocessor } from '@riotjs/compiler';
import postcssLoadConfig from 'postcss-load-config';
import postcss from 'postcss';

// Setup postcss preprocessor, if not already set.
// Get config with loaded modules.
const postcssConfig = postcssLoadConfig.sync().plugins;
// Instantiate processor instance.
const postcssProcessor = postcss(postcssConfig);
// Register preprocessor.
registerPreprocessor('css', 'postcss', function(_code, _options) {
  return {
    code: postcssProcessor.process(_code).css,
  };
});
```

Do note that only synchronous postCSS plugins can be used which limits you quite a bit in what you can do. For example `autoprefixer` will work, but `postcss-preset-env` won't. It will give you the following error: `Error: Use process(css).then(cb) to work with async plugins`.

Unfortunately I'm still running into a problem. I'm using `rollup` in combination with `rollup-plugin-serve` and `rollup-plugin-livereload`. When I make a change and the app rebuilds it will obviously register the preprocessor again, this will however throw an error: `The preprocessor postcss was already registered before`. Wouldn't it be nicer if it overwrote the existing one and threw a warning at most, or at least provide a function to deregister the preprocessor. Because currently I have it wrapped in a try-catch block that never throws an error.

**Comment by GianlucaGuarini** [comment]
@RedKenrok can you please set up a demo repo showing the issue? I will try to help you with a PR. Thank you

**Comment by RedKenrok** [comment]
Tried setting up a demo, but the issue wasn't there. As it turns out the error only occurs when making a change to the `rollup.config.js` itself. Which obviously makes the script run again and add register the preprocessor again. Honestly that's not a big deal at all. If you make a change to your build configuration you should restart the entire process anyway.

Sorry for all the trouble and thank you for all the help. I'm really enjoying using Riot.
