### ISSUE TITLE
Wrong compilation for in parentheses expression

### ISSUE THREAD

**Issue by EliteXXL** [riot/compiler#134]
I tried to use this expression `{ (!state.property).toString() }` and it compiled to `{ scope.(!state.property).toString() }`. It does the same without the exclamation mark.

[Codesandbox](https://codesandbox.io/s/riotjs-4-bug-template-w47d6)

[x] bug

**Comment by GianlucaGuarini** [comment]
thank you for reporting this issue. I will try to fix it asap.

**Comment by EliteXXL** [comment]
Thank you for fixing it so rapidly!
