### ISSUE TITLE
"src" attribute for <style> and <script>

### ISSUE THREAD

**Issue by Kal-Aster** [riot/compiler#136]
Hi!
I think that the title is quite exhaustive :P

The meaning of this is to have different files to manage css, html and js separatedly.
It would be easier to read and mantain

[x] Feature request

**Comment by GianlucaGuarini** [comment]
this topic was already discussed [here](https://github.com/riot/riot/issues/2809). At moment I don't think this feature is something I want to add to the framework. Thank you for your asking it anyway

**Comment by Kal-Aster** [comment]
Actually it is something different from what is discussed [there](https://github.com/riot/riot/issues/2809), because i meant to use the "src" attribute to point a script or a style for compilation.

**Comment by GianlucaGuarini** [comment]
@Kal-Aster just use import calls as suggested:
```riot
<my-tag>
  <p>{ state.message }</p>

  <script>
    import MyTagLogic from './my-tag-logic'
    export default () => MyTagLogic
  </script>
</my-tag>
```

**Comment by Kal-Aster** [comment]
Nice workaround.

What about style?

**Comment by GianlucaGuarini** [comment]
@Kal-Aster If you have chosen Riot.js it means you like to put javascript and CSS into the same file. Your request of using `src` on style/script files makes not much sense. However if you want to use external css files use css imports
```riot
<my-tag>
  <style>
    @import './path/to/your/component.css'
  </style>
</my-tag>
