### ISSUE TITLE
Importing scss inside of riot component

### ISSUE THREAD

**Issue by markgarrigan** [riot/compiler#138]
The riot docs show this being possible...

```
<my-component>
  <p>{getMessage}</p>

  <style type="scss">
    import 'color/vars'

    p {
      color: $primary;
    }
  </style>

  <script type="ts">
    export default {
      getMessage():string {
        return 'hello world'
      }
    }
  </script>
</my-component>
```

However, the import statement is incorrect syntax. And if you use the correct `@import` syntax it still doesn't work. Scss can't find that file. It does work if you include the full absolute path to the file you're importing. I'm assuming this has to do something with where sass is looking for files to import.

**Comment by markgarrigan** [comment]
I can get it to work if I register the component path with sass includePaths. But includePaths doesn't take a glob so I'd have to manually add every components path.

A workaround would be to have all the scss files in one directory. But, I was hoping to have all component files together in their own directory.

```
const { registerPreprocessor } = require('@riotjs/compiler')
const sass = require('sass')

registerPreprocessor('css', 'scss', function (code, { options }) {
  const { file } = options

  console.log('Compile the sass code in', file)

  const { css } = sass.renderSync({
    data: code,
    includePaths: [__dirname + '/src/app']
  })

  return {
    code: css.toString(),
    map: null
  }
})
```

**Comment by GianlucaGuarini** [comment]
You can try passing the folder path to the sass compiler for example:

```js
const { registerPreprocessor } = require('@riotjs/compiler')
const { dirname } = require('path')
const sass = require('sass')

registerPreprocessor('css', 'scss', function (code, { options }) {
  const { file } = options

  console.log('Compile the sass code in', file)

  const { css } = sass.renderSync({
    data: code,
    includePaths: dirname(file)
  })

  return {
    code: css.toString(),
    map: null
  }
})

```

**Comment by markgarrigan** [comment]
Oh. That's a good idea! I'll give that a shot and report back.

**Comment by markgarrigan** [comment]
https://github.com/riot/compiler/issues/138#issuecomment-765185284 works great for my needs. Thanks for pointing me in the right direction. I'll probably open a PR on the riot website repo to update the docs with a little more detail on this and fix the scss import syntax.
