### ISSUE TITLE
Give access to riot.compiler(tag,true) unpacked results

### ISSUE THREAD

**Issue by nippur72** [riot/compiler#14]
It was discussed [here](https://github.com/riot/riot/issues/1097) and also [here](https://github.com/riot/riot/issues/1273).

In brief, there is need for a `riot.compile()` function that compiles HTML-only templates (no code) and that returns the result of the compilation in a manageable format.

This is to support the scenario of template files separated from code (opposed to .tag files) as some of us are doing for ES6 / TypeScript (see [RiotTS](https://github.com/nippur72/RiotTS)).

Currently we use an hack to extract the results from `riot.compile(tag,true)`, but it would be nice if there was a specific compiler API method.

The current hack is this:
```javascript
var compiled = riot.compile(template,true);
var r = compiled.indexOf("riot.tag(");
var stripped = compiled.substr(r+9);
var x = stripped.lastIndexOf(", function(opts) {");
stripped = stripped.substr(0,x);
var compiledResultArray = eval("["+stripped+"]");
```

**Comment by Havunen** [comment]
+1

**Comment by aMarCruz** [comment]
For html only you can use:
```
var compiler = require('riot-compiler')
var html = compiler.html(htmlSource, options)
```
for options you can use `whitespace` (preserve cr/lf) or `compact` (remove space between `>` and `<`), `type` or `parser`, etc. (almost same as riot-cli).

**Comment by aMarCruz** [comment]
@nippur72, @Havunen, compiler v2.3.13 is out and includes support for an additional option: `entities`
Send this as `true` and the compile function will return an object with 4 properties type string:
`{tagName, html, css, attribs, js}`.
The parts defaults to empty strings, are unescaped and include raw (normalized) newlines and backslashes.

There are docs (wip) in the [doc folder](https://github.com/riot/compiler/tree/dev/doc) about this version.

**Comment by aMarCruz** [comment]
I forgot: Soon, this option may be used with `riot.compile` too:
```js
var obj = riot.compile(tag_string_or_url, false, {entities: true})
```
The `riot.compile` function will support an additional parameter: the options for compile.
This is in test yet, support will be merged on the `dev` branch of riot.

**Comment by nippur72** [comment]
:+1: fantastic

**Comment by aMarCruz** [comment]
@nippur72 thanks, I will update doc/guide.md soon.

**Comment by aMarCruz** [comment]
[doc/guide](https://github.com/riot/compiler/blob/master/doc/guide.md) and [doc/attributes](https://github.com/riot/compiler/blob/master/doc/attributes.md) are updated.
