### ISSUE TITLE
template element related: generated style has incorrect selector; elements of template does not receive is= tagname to be selected

### ISSUE THREAD

**Issue by qlbit-com** [riot/compiler#148]
I believe it is a compiler issue. 

reproduced here: https://plnkr.co/edit/hoERoykakbT5h6s4

Rendering test-tag **as is** and **in scope of template element**
```
<my-tag>
    <test-tag></test-tag>
    <template is='test-tag'></template>
</my-tag>

```

Code and rendering
![2021-06-14_17h33_37](https://user-images.githubusercontent.com/50788857/121962606-f5298880-cd36-11eb-8497-81ce39ad09a1.png)

Proposal to fix template rendering
![2021-06-14_17h39_39](https://user-images.githubusercontent.com/50788857/121964240-3ae75080-cd39-11eb-8980-e2f397bd2362.png)

**Comment by qlbit-com** [comment]
actually,  `<div is="test-tag>` is rendered properly.

![image](https://user-images.githubusercontent.com/50788857/122142282-22506680-ce1d-11eb-8926-0aba4f494191.png)

I think extra selector needs to be added specifically for template element, and whole css should be like
```
  test-tag .foo,[is="test-tag"] .foo,[is="test-tag"].foo{ background : red } 
```
one [is="test-tag"] with whitespace, other without whitespace

**Comment by GianlucaGuarini** [comment]
`<template is='test-tag'>` is not a Riot.js feature, it's a side effect. Please check https://github.com/riot/riot/issues/2899#issuecomment-803285190
