### ISSUE TITLE
babel compiler destroys this references within a tag

### ISSUE THREAD

**Issue by appedemic** [riot/compiler#15]
Consider this tag file (test.tag):
```html
<test>
  <script>
    this.x = 1;
  </script>
</test>
```
I am compiling stuff using gulp, browserify, babelify and riotify to a single bundle, using babel-core > 6.0.2. I am using the "type: babel" compiler. When looking at the output, the tag is compiled to:

```js
module.exports = riot.tag2('test', '', '', '', function(opts) {
undefined.x = 1;
});
```
Somehow all references to _this_ are replaced by _undefined_. It has to do something with the _es2015_ preset used. When I change the preset in the compiler from _es2015_ to _stage-0_, the correct output is generated:

```js
module.exports = riot.tag2('test', '', '', '', function(opts) {
this.x = 1;
});
```

**Comment by appedemic** [comment]
In specific, the plugin _transform-es2015-modules-commonjs_ is causing this behaviour

**Comment by GianlucaGuarini** [comment]
@appedemic thanks for your explanation have you tried submitting the issue also on babeljs? I am not sure it's related to riot

**Comment by appedemic** [comment]
It is a babel thing, I'm creating a pull request right now

**Comment by GianlucaGuarini** [comment]
@appedemic ok thank you so much, can we close this issue?

**Comment by appedemic** [comment]
Not exactly, babel says this is expected behaviour for ES6. Because the babel transpiler will consider the code block taken from the tag as a module and it will not allow toplevel references to _this_.

I need to think on this for a moment, but if this is indeed how ES6 should behave, it means we cannot use _this_ to reference to the tag object, unless the code within the <script> tag is somehow wrapped in a function expression.

**Comment by appedemic** [comment]
One fix would be to omit the transform-es2015-modules-commonjs plugin from the list, but this means that the preset es2015 cannot be used and instead you need to make a list of plugins, including all the plugins from the es2015 preset, except the modules-commonjs one.

**Comment by GianlucaGuarini** [comment]
>  babel transpiler will consider the code block taken from the tag as a module and it will not allow toplevel references to this.

It does not make sense to me because your `this` does not mean `undefined` and it should not even be touched by babel. Babel should transpile only the code that needs to be converted into valid es5 leaving the default es5 blocks untouched.

**Comment by appedemic** [comment]
"Babel assumes that all input code is an ES6 module. ES6 modules are implicitly strict mode so this means that top-level this is not window in the browser nor is it exports in node." - BabelJS

I'm switching back to babel 5 for now, need to get some work done

**Comment by fkei** [comment]
+1

**Comment by Havunen** [comment]
@appedemic We had this exactly same issue also and found same thread about module scope (and reverted to 5.8 :D ).

One solution would be that riot should send the function wrapper also to babel instead only the contents. currently its sending only content and then wrapping it into tag2 function. But if this function along its content is sent to babel then it will produce expected end result, because it knows "this" is inside funtion scope not module.

**Comment by appedemic** [comment]
Yeah, if the entire "riot.tag2(....)" output would be processed by babel, the _this_ would not be toplevel and will not be converted to _undefined_ by babel. Would it be easy to do this in the compiler? 

I might have some time tomorrow to take a look at this solution.

**Comment by appedemic** [comment]
I've made a patch that adds the function wrapper to the compile stage. In the case of babel the function wrapper is passed to the compiler, in the other cases the wrapper is added after compiling the inner block.

**Comment by appedemic** [comment]
Nope, this patch really destroys compilation, but I've got a solution, will prepare a new patch... It's a bit dirty but it will probably work

**Comment by appedemic** [comment]
I've changed the babel parser to add a temporary wrapper function around the code and remove it directly after compiling. Tests are passing :)
