### ISSUE TITLE
Unable to read the custom parsers options

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/compiler#16]
I am working in the branch `custom-parsers-options` but the method `getAttr` seems to be buggy because it does not allow to get attributes like `<style type="sass" options="{ 'val': true  }"> `. @aMarCruz any help?

**Comment by aMarCruz** [comment]
@GianlucaGuarini , yeah, it was written for literals, I will fix this.

**Comment by aMarCruz** [comment]
@GianlucaGuarini , I change the regexp for `getAttr` in the `dev` branch. It can handle inner quotes:
` options="{ 'val': true }"` or ` options="{ \"val\": true }"` or ` options='{ "val": true }'`.
NOTE: unquoted or single quoted name is __invalid__ JSON. `getParserOptions` is unescaping double quotes, but this avoid using double quotes in strings, e.g. `{ "str": "\"big\"" }`
Unquoted objects/strings must not contain spaces.

For values in `script` and `style` tags, the compiler (and therefor `parseAttr`) can not handle the `>` char, even in quoted values.

**Comment by GianlucaGuarini** [comment]
Ok thanks I will test it and let you know if I have still problems
