### ISSUE TITLE
Unclear error when compilation preprocessor isn't available

### ISSUE THREAD

**Issue by davidpelaez** [riot/compiler#17]
Assume `riot --type coffee --expr kids.tag`, if you don't have coffeescript installed you would get `TypeError: Cannot read property 'compile' of null`. 

It would appear this is because it's trying to require something that ends up being null/undefined because if cannot be resolved.

Adding a small detection on this requires would probably enable more precise error reporting without much complication.

Moved here as per @GianlucaGuarini request.

**Comment by aMarCruz** [comment]
@davidpelaez , thanks. riot-compiler v2.3 already has [parser detection](https://github.com/riot/compiler/blob/dev/lib/parsers.js#L76), we are working in improve this.

@GianlucaGuarini , I think it is better include a user-friendly message in the cli. For one-time detection? what do you think?

**Comment by GianlucaGuarini** [comment]
> I think it is better include a user-friendly message in the cli for one-time detection. what do you think?

@aMarCruz yes of course but I need to know the errors coming from the compiler, is there a way to make that method public? And how do I know that `es6` requires `babel@5.8` ?  I think we can find a really smooth solution here ;)

**Comment by aMarCruz** [comment]
@GianlucaGuarini , parsers._req is called with the type (es6, coffee, etc) and returns null without throw error if require fails, and babel has a version property.

**Comment by GianlucaGuarini** [comment]
Ok I will try to implement this feature in the `riot-cli` thank you

**Comment by GianlucaGuarini** [comment]
BTW @aMarCruz I would also like to implement 3 new options to export only `css`, `js` or `html` from the tags compiled. Do we have already a method in the compiler to get these strings?

**Comment by aMarCruz** [comment]
no, but is easy in the compile function if you pass an option for this, returns an object instead a string. But for multiple tags?

**Comment by GianlucaGuarini** [comment]
It sounds great! 
Basically the only thing I need is to get any of [these variables](https://github.com/riot/compiler/blob/dev/lib/core.js#L586). I will let you decide what's the best way to achieve it

**Comment by aMarCruz** [comment]
ok, an object with html, css, js...attributes too? and the name for the option?

**Comment by GianlucaGuarini** [comment]
@aMarCruz What do you mean?

**Comment by aMarCruz** [comment]
with an option, e.g. `opts.separate`, compile() can return an array of objects instead a js string

**Comment by GianlucaGuarini** [comment]
Yeah it 's ok thanks

**Comment by aMarCruz** [comment]
I push the code in the `feature/parts` branch

**Comment by GianlucaGuarini** [comment]
you can call the option `opts.entities = true`

**Comment by aMarCruz** [comment]
done. I complet the test and merge tomorrow. good night :)

**Comment by GianlucaGuarini** [comment]
I will work on it this weekend so take it easy

**Comment by GianlucaGuarini** [comment]
This issue was fixed in the `riot-cli`
