### ISSUE TITLE
there is no option that does not change `:host` to `my-tag, [is="my-tag"]` for web components.

### ISSUE THREAD

**Issue by nibushibu** [riot/compiler#177]
I have recently been trying to mount Riot components as Web Components using https://github.com/riot/custom-elements. So far, most of it has been working well, but I have some concerns regarding the compilation of styles.

When mounting Riot components as web components using custom-elements, if compiler convert the `:host` written in the `<style>` of my component file(ex. my-tag.riot) to `my-tag, [is="my-tag"]`, that style will not be applied in shadowDOM. 

Shouldn't there be an option to keep `:host` as it is even after compilation?

**Comment by GianlucaGuarini** [comment]
I don't know how you are compiling your tags but passing the `scopedCss` [option](https://github.com/riot/compiler/blob/main/src/index.js#L38) to the compiler should allow you to disable the css prefixing.
See also https://github.com/riot/compiler/pull/168
