### ISSUE TITLE
Utils access

### ISSUE THREAD

**Issue by Kal-Aster** [riot/compiler#179]
Is there any way to get access to the utilities functions like [this one](https://github.com/riot/compiler/blob/main/src/generators/template/utils.js#L263)?

**Comment by GianlucaGuarini** [comment]
I might expose the `src` folder and publish it for advanced users. In that case you might have access to the internals via `@riotjs/compiler/src/...`

**Comment by Kal-Aster** [comment]
This should work, I don’t see any downside

**Comment by Kal-Aster** [comment]
It works, thank you
