### ISSUE TITLE
Probably a mistake?

### ISSUE THREAD

**Issue by Kal-Aster** [riot/compiler#180]
I was reading the source code and found a function that says in the doc that should return a boolean or undefined but it actually does not return nothing (hence it returns undefined always).
The function is [this one](https://github.com/riot/compiler/blob/main/src/generators/template/utils.js#L119C1-L127C2):
```
/**
 * The this expressions should be replaced with the scope
 * @param   { types.NodePath } path - containing the current node visited
 * @returns { boolean|undefined } return false if we want to stop the tree traversal
 */
function visitThisExpression(path) {
  path.replace(scope)
  this.traverse(path)
}
```

I don't know if this could cause any problem, but I thought it would be worth it to mention.

**Comment by GianlucaGuarini** [comment]
thank you that was a harmless mistake :P
