### ISSUE TITLE
babel and 'use strict'

### ISSUE THREAD

**Issue by appedemic** [riot/compiler#19]
When using the babel compiler (babel 6), babel adds a "use strict" to the code, which is removed by the riot-compiler. My babel version however, outputs 'use strict' with single quotes, which is not caught by the regex. 

I've created a patch and also added a test case for the babel this issue (#15). It passes, but comes awfully close to the 2000ms cutoff on my machine.

**Comment by GianlucaGuarini** [comment]
Yes pull request please adding your tests and I will make a new riot release soon ;)

**Comment by appedemic** [comment]
I did but travis is failing and the babel is complaining about the "presets". Could it be that the travis tests are only run using babel 5.x?
