### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by weepy** [riot/compiler#3]
hey - i've spent about an hour messing about with whitespace issues in .tag files. I know it's in the docs, but it's kinda unexpected. Are you planning to improve this for 2.3 ?  I worry that this kind of thing will hurt adoption.

**Comment by aMarCruz** [comment]
hi @weepy , yes
see the code preview in the 230-alpha1 branch, please, and the .tag file in test/server-specs/fixtures/includes.tag

**Comment by aMarCruz** [comment]
@weepy , the new compiler is less restrictive with whitespace, please make your tests with it.
There are no docs yet but you can examples in the [fixtures](https://github.com/riot/compiler/tree/dev/test/specs/fixtures) and the [parsers](https://github.com/riot/compiler/tree/dev/test/specs/parsers) folders.

Make your test with the new version please.
There are docs (WIP) about whitespace in https://github.com/riot/compiler/blob/dev/doc/backslashes_and_whitespace.md

**Comment by aMarCruz** [comment]
@weepy, compiler v2.3.13 is out.
This update should offer consistency and more flexible tag definitions, internal and external.
Also, from this version the `<pre>` tag preserves whitespace.

The doc/backslashes_and_whitespace.md was renamed to doc/guide.md and first section is about indentation, with a brief example. I hope to integrate this documentation on riot, if anyone edit it.

note: This version fix an issue with newline preservation which break tests in the riot repository, so if you using these please update your dev copy of riot (the change is in https://github.com/riot/riot/blob/dev/test/specs/compiler/html.js#L50).

**Comment by aMarCruz** [comment]
[doc/guide](https://github.com/riot/compiler/blob/master/doc/guide.md) and [doc/attributes](https://github.com/riot/compiler/blob/master/doc/attributes.md) are updated.

**Comment by aMarCruz** [comment]
I'll close this issue now, feel free to reopen it if you consider it necessary.
