### ISSUE TITLE
Consistency in exposed APIs

### ISSUE THREAD

**Issue by aMarCruz** [riot/compiler#37]
@riot/owners ,
with the recent additions, we have inconsitent interfaces for the compiler functions `html`, `style`, and `js`, of the node version.
Even now, I have problems remember the correct order. This is:

```js
compile (source, compilerOptions, url*)
html    (source, compilerOptions, expressions*, url*)
style   (source, tagName, parserName, scopedFlag*, parserOptions*, url*)
js      (source, compilerOptions, parserName, parserOptions*, url*)
```

My proposal is to change the API to this:
```js
compile (source, compilerOptions, url)
html    (source, compilerOptions, url, expressions)
style   (source, compilerOptions, url, parserName, parserOptions, tagName, scopedFlag)
js      (source, compilerOptions, url, parserName, parserOptions)
```

...or we can use a plain object for additional parameters:
```js
function (source, compilerOptions, url, additionalOptions)
//e.g.
var css = compiler.style(src, opts, url, { tagName: 'my-tag', scoped: true })
```

which has the advantage that you can add more parameters as needed, without disturbing a previous API.

I know this ***can be*** a breaking change, but these function are not documented yet, and the parameters marked with `*` are new to v2.3.x (I can remove an internalFlag of `html`).
The main change is in the `style` function, note "tagName" and "scopedFlag" is used internally to call scopedCSS.

*The parsers API:*
```js
html (source, options, url)
css  (tagName, source, options, url)
js   (source, options, url)
```

again, the parameter "tagName" of `parsers.css` is not used by any riot parser, it is used when "scopedFlag=true" by the internal scopedCSS function, so I think is better change this to `(source, options, url, tagName)` or even remove the "tagName" parameter.

**Comment by cognitom** [comment]
@aMarCruz How about this option?:

```js
compile (sourceOrUrl, options*)
html    (sourceOrUrl, options*)
style   (sourceOrUrl, options*)
js      (sourceOrUrl, options*)
```

I think we could manage to keep it without breaking change. For example we may wrap like this:

```js
function compileCSS(style, tag, type, scoped, opts) {
  if (typeof tag == 'object')
    return compileCSS2(style, tag)
  opts.tag = tag
  opts.type = type
  opts.scoped = scoped
  return compileCSS2(style, opts)
}
function compileCSS2(source, opts) {}
```

After the major version bump, we could remove the wrapper.

BTW, I'm not sure we should separate `compilerOptions` and `parserOptions`.

**Comment by aMarCruz** [comment]
@cognitom , I'm glad to read you.
Yes, this may be a solution, but `compilerOptions` are for the compiler (`whitespace`, `compact`, etc) and `parserOptions` are user options for parsers, the compiler does not use them and there's no way to differentiate.

**Comment by cognitom** [comment]
I see. `parser` options could be one of the compiler option:

```js
var options = {
  whitespace: true,
  compact: true,
  scoped: true,
  parser: {
    ...
  }
}
style(sourceOrUrl, options)
```

Some of the properties may not used in the compiler, it'll be just ignored. Anyway, it's just an idea :-)

**Comment by aMarCruz** [comment]
Sorry by the delay. You have the idea. I'm talking with @rsbondi in the Riot Devs about this.
