### ISSUE TITLE
Turn attrs into an object

### ISSUE THREAD

**Issue by nippur72** [riot/compiler#38]
When a tag is compiled, `attrs` are stored as a plain string and later at runtime they are processed with the `walkAttributes` function (during the `mount` event).

I suggest to move attribute parsing into compiler, outputting attributes as a plain javascript object (key-value pairs) so it's easier and faster to process them at runtime.

**Comment by aMarCruz** [comment]
@nippur72 , you are right and I have it in my TODO for the next version. It is one reason for `riot.tag2`, avoiding breaking change.

**Comment by aMarCruz** [comment]
maybe in v2.4, which also will include the remotion of `__` for boolean attributes. I need write code to handle these changes in `riot.tag` transparently.

**Comment by GianlucaGuarini** [comment]
I also would love to see this feature landing in riot@3.0.0

**Comment by GianlucaGuarini** [comment]
the attributes can be spreaded with v4.0.0. `<p ...{attributes}>`. I am closing this issue
