### ISSUE TITLE
Compiler preview 1

### ISSUE THREAD

**Issue by aMarCruz** [riot/compiler#4]
@tipiirai , @GianlucaGuarini , @cognitom , @rsbondi ,
@riot/owners ,
please see the preview of the compiler in the 230-alpha1 branch.

I think about 60% is done (the heavy parts).

### Points of interest:
* almost free indentation and style.
* better support/detection of expressions (there's no solution for `>` in unquoted attributes in html markup).
* multiple `script` tags (different "type" attribute) combined with one untagged script block.
* experimental support for script inclusion (with the "src" sttribute) from the file system at compile-time.
* multiple style blocks of various types. scoped convertion is applied after the preprocessing with external tools.
* changed logic to scoped styles, now `:scoped` is replaced with the tagname and the riot-tag attribute, there's no reordenation.
* support for full iso-8859-1 charset in attribute names.
* precompiled expressions.
* evaluation errors are logged (with console.error, optional feature).
* source filename is writted in the generated code (optional).

## Precompiled expressions

The compiler replaces the expressions with a hash inside fix delimiters `#@` and `#` (invalid in js, but valid in html markup) and append an object to register the functions at creation-time, in a new riot.tag2 function. With this, there's no need to call the Function() ctor and there's no problem with Google security restrictions.
Modified tmpl/brackets functions supports these new form and can compile the expressions at runtime with custom brackets, too (we can have mixed mode expr in source).
e.g.
```
riot.tag2('my-box', '<h1>#@091103179#</h1>', '', '', function(opts) {
  this.box = {
    title: "Hello",
  }
}, {"@091103179":function(G){return ("box"in this?this:G).box.title}});
```
riot.tag2 implementation:
```
riot.tag2 = function (name, html, css, attrs, fn, pce) {
  if (css) injectStyle(css)
  if (pce) tmpl.insert(pce)    // <-- register precompiled expressions with tmpl module
  tagImpl[name] = { name: name, tmpl: html, attrs: attrs, fn: fn }
  return name
}
```

This compiler does more than the older one, but the performance and code size is almost the same. At run-time there are gains in speed, and the generated functions are lighter and (I hope) memory-friendly.
With pure precompiled expressions there's no need to include the full tmpl/brackets, only the evaluation part (~30% of the full code).

I'm including a simple test of performance in test/perf.js

Please let me know what do you think.

**Comment by aMarCruz** [comment]
btw: I change the logic for escaped brackets. In previous version, the escape char is preserved, in this version, the escape char is removed, before passed to the external preproc (riot.parser).
Expressions prefixed with a caret (e.g. `{^ foo }`) are not passed to the preproc (to avoid problems with coffescript and shorthand).

**Comment by GianlucaGuarini** [comment]
You've done a great job, I have just a couple of questions: 
 1. _I see `tmpl.js` and `bracket.js` in your branch. Does the new compiler depend on these files?_ If yes then you should update them in [this repo](https://github.com/riot/tmpl) avoiding to include them here. Eventually they could be included as npm dependency if you really need it.
 2. _Can we make the compiler a standalone script that could be easily included via npm in the `riot-cli` repo and in riotjs?_ This probably means that you should provide several build files ( in a `dist` folder ) like we have already done [here](https://github.com/riot/route/tree/master/dist), [here](https://github.com/riot/observable/tree/master/dist) and [here](https://github.com/riot/tmpl/tree/master/dist)
 3. _The repos `riot-tmpl`, `riot-observable`, `riot-route` were already successfully [included in the riot core](https://github.com/riot/riot/blob/dev/lib/riot.js#L3-L8) could you ping me once you think we are ready to test it in the riot core?_
 4 _Could you publish (once you are ready) a `riot-compiler` release on npm so I could include it in `riot-cli`?_ Please tell me your npm username so I will give you the owner rights on https://www.npmjs.com/package/riot-compiler and https://www.npmjs.com/package/riot-tmpl

I see a lot of improvements here and I would like to thank you for all your effort and your time. I am looking forward to seeing your work included in the main riot repo

**Comment by aMarCruz** [comment]
Hi @GianlucaGuarini ,
1) the inclusion is temporal for testing and rapid modifications of brackets and tmpl, and yes, the compiler depends on both modules (tmpl depends on brackets for compilation of expressions, not for evaluation).
2) Yes. So, riot-compiler will be a private module serving to riot core and riot-cli ?
3) Yes. riot core needs some tweaks to integrate the new compiler, I'm working on this. Please send me your email to amarcruz1 at gmail dot com.

**Comment by aMarCruz** [comment]
New PR in 230-alpha1.
Output of `make perf` in virtual machine with 1 proc, 2.8 Ghz, 4GB RAM:
```
Testing each compiler with 6 files, 10x1500 iterations (90000 total)
Testing compiler v2.2.4 ...
Testing compiler v2.3.0 ...

Results        Compiler 2.2.4   Compiler 2.3.0
------------   --------------   --------------
box         :        2200            2544
input-last  :         702             904
mixed-js    :         844             734
same        :         656             623
scoped      :        1468            1077
timetable   :         671             607
TOTAL       :        6541            6489

Execution time of 5 expressions & 3 shorthands, 100000 iterations each
tmpl v2.2.4 ...
tmpl v2.3.0 ...

Results        tmpl 2.2.4   tmpl 2.3.0
------------   ----------   ----------
Expressions :         560          234
Shorthands  :         390          124
TOTAL       :         950          358

compiler time for v2.3.0 includes compilation of expressions.
both tmpl times excludes compilation.
minimum & maximum times are removed in all tests.
```

**Comment by GianlucaGuarini** [comment]
@aMarCruz I gave you the owner rights on the packages `riot-compiler` and `riot-tmpl` guessing this is your npm account https://www.npmjs.com/~amarcruz so now you can publish alpha/beta releases.
Please consider that now we have on npm:
  - `riot-route` 2.3.0-beta.3
  - `riot-observable` 2.3.0-beta

This means that these packages are complete and ready for `riot` 2.3.0-beta ( that will be released as soon as all the others submodules will reach the 2.3.0-beta version ), try please to follow the same versioning convention for `riot-tmpl` and `riot-compiler`.

> 1) the inclusion is temporal for testing and rapid modifications of brackets and tmpl, and yes, the compiler depends on both modules (tmpl depends on brackets for compilation of expressions, not for evaluation).

Ok I got it

> 2) Yes. So, riot-compiler will be a private module serving to riot core and riot-cli ?

No `riot-compiler` will be like all the other riot submodules. 
  - __It can be used as standalone package__ ( mainly serverside ) to compile riot tags exporting its internal methods so our users will be able to use it as they prefer extending the riot core functionalities
  - __it can be included in riot__ to compile tags in runtime and assuming that tmpl.js and brackets.js were already loaded in the same scope

> 3) Yes. riot core needs some tweaks to integrate the new compiler, I'm working on this. Please send me your email to amarcruz1 at gmail dot com.
you can get my email from [my profile](https://github.com/GianlucaGuarini) just let me know once you are done ;)

**Comment by tipiirai** [comment]
This is purely awesome! So much better than the current compiler in so many ways. Great job indeed.

I'm hoping to understand these two improvements a bit more:

> better support/detection of expressions  
> support for full iso-8859-1 charset in attribute names.

A quick example would be the best. 

I really like this. Thank you.

**Comment by aMarCruz** [comment]
@GianlucaGuarini , @tipiirai thanks.

compiler 2.2.3 fails with this:
`foo={ bar: c=='}' } bar={ c=='"' } other="{ 'x' }" baz="{ a>c }"`
new compiler will parse these (last expression with '>' needs quotes).
iso-8859-1 includes characters 0x0a -0xff, so `buzón="INBOX"` is valid.

here is an example with multiple script blocks, including one loaded from the filesystem:
https://github.com/riot/compiler/blob/230-alpha1/test/server-specs/fixtures/includes.tag
the output is in
https://github.com/riot/compiler/blob/230-alpha1/test/server-specs/expect/includes.js
this have comments and format not accepted by v2.2.3

There are restrictions: you can't use comments in expression, nor characters in the regex `[<>\w'"]` for custom brackets. I'll publish a little guide soon.

**Comment by tipiirai** [comment]
Thank you for the info. Seems perfect to me.

**Comment by GianlucaGuarini** [comment]
@aMarCruz We are almost ready to publish [riot 2.3.0](https://github.com/riot/riot/issues/1063#issuecomment-148926047) and the new `riot-compiler` is the only piece still missing. Would you recommend making the new release still with the old compiler so you will have a bit more time to work on the new one? Please let me know if you need any help either on `riot-tmpl` or on the compiler

**Comment by aMarCruz** [comment]
Sorry to all, I'm really having busy days. The new tmpl & compiler is on `npm` now, please do `npm update` if you want test locally.

**Comment by GianlucaGuarini** [comment]
The new compiler got successfully upgraded in `riot-cli` ;)

**Comment by aMarCruz** [comment]
Yeah, thanks. Now my problem is in the browser :)

**Comment by cognitom** [comment]
@aMarCruz great! I'll try these asap :)

**Comment by aMarCruz** [comment]
Thanks @cognitom , sorry this is not working in the browser yet :(
I will fix the issues tonigh or tomorrow morning.
