### ISSUE TITLE
2.3.18 compiles down to 'this' being undefined

### ISSUE THREAD

**Issue by mattbailey** [riot/compiler#41]
When I compile a tag with 2.3.18, ``this`` within a tag becomes undefined, downgrading to 2.3.13 seems to resolve the issue.  Quickly tested with just a console.log(this) within a tag.

I am using webpack with riotjs-loader and babel 6, I have tags with ``<script type="babel">`` in them, but it doesn't seem to really make a difference.

The compiled tags come out looking like this, for example:

```	  var parent = undefined.parent;```

**Comment by GianlucaGuarini** [comment]
Use this preset https://github.com/riot/babel-preset-es2015-riot we are aware of this issue and it comes from babel we have solved it in [this way](https://github.com/riot/babel-preset-es2015-riot/blob/master/index.js#L21)

**Comment by mattbailey** [comment]
I am using that preset, my .babelrc looks like this:

```json
{
  "plugins": [
    "transform-es2015-modules-commonjs",
    "transform-runtime"
  ],
  "presets": ["es2015-riot"]
}
```

webpack.conf.js:
```javascript
const webpack = require('webpack')

const namedBranches = [
  'develop',
  'test',
  'integration',
  'master',
  'staging'
]

function getEnv() {
  if (process.env.CI_BRANCH) {
    return (namedBranches.include(process.env.CI_BRANCH)) ? process.env.CI_BRANCH : 'develop'
  }
  return 'develop'
}

module.exports = {
  cache: true,
  watch: false,
  entry: [
    './src/polyfills.js',
    './src/env/' + getEnv() + '.js',
    './src/entry.js'
  ],
  output: {
    path: __dirname + '/dist/',
    filename: 'bundle.js'
  },
  devtool: 'source-map',
  plugins: [
    new webpack.ProvidePlugin({
      riot: 'riot'
    })
  ],
  module: {
    preLoaders: [
      {
        test: /\.tag?$/,
        exclude: /node_modules/,
        loader: 'riotjs-loader',
        query: { type: 'babel' }
      }
    ],
    loaders: [
      {
        test: /\.js|\.tag$/,
        exclude: /node_modules/,
        include: /src/,
        loader: 'babel',
        query: {
          plugins: [
            'transform-es2015-modules-commonjs',
            'transform-runtime'
          ],
          presets: ['es2015-riot']
        }
      }
    ]
  }
}
```

**Comment by GianlucaGuarini** [comment]
You need to remove `"transform-es2015-modules-commonjs"` from your plugins

**Comment by mattbailey** [comment]
That appears to have worked, thanks @GianlucaGuarini !!!

**Comment by GianlucaGuarini** [comment]
No prob I was fighting against the same issue for 3 days
