### ISSUE TITLE
v2.3.21 Fails to find pre-processors

### ISSUE THREAD

**Issue by JonathanWolfe** [riot/compiler#44]
When using `v2.3.21`, all pre-processors fail to be found and cause an infinite hang (no `EXIT` code broadcasted).

**Comment by aMarCruz** [comment]
@JonathanWolfe , get me details please. Your tag. In cli, server side rendering, browser?

**Comment by JonathanWolfe** [comment]
Any tag at all.
`npm install riot@latest`. Should install `riot-cli@2.3.14` & `riot-compiler@2.3.21`
The below `riot.config.js`:
```js
export default {
	from: 'src/templates',
	to: 'compiled/js/templates.js',
	compact: true,
	expr: true,
	modular: true,
	colors: true,
	exclude: [ 'css' ],
	// js parser
	type: 'babel',
};
```
Run the command: `riot --config riot.config.js`

**Comment by aMarCruz** [comment]
@JonathanWolfe , maybe related to #45, please use v2.3.20. I'm working on a fix.

**Comment by aMarCruz** [comment]
Please test with v2.3.22, it is already in npm.

**Comment by JonathanWolfe** [comment]
`2.3.22` is working for me on the server now. Browser side uses `riot@2.3.13` script from cdnjs.com and still fails so I think you've fixed the issue.

**Comment by GianlucaGuarini** [comment]
@JonathanWolfe just run `npm uninstall riot -g && npm install riot -g`

**Comment by JonathanWolfe** [comment]
@GianlucaGuarini Doing that isn't gonna update https://cdnjs.cloudflare.com/ajax/libs/riot/2.3.13/riot.min.js :)

**Comment by GianlucaGuarini** [comment]
@JonathanWolfe ok so you are using the runtime compiler as well. In that case we will release soon a patch release hold on please
