### ISSUE TITLE
v2.3.22 not working in browser

### ISSUE THREAD

**Issue by jrschreiber** [riot/compiler#49]
Since ```d2843fe81e2a9bb5ac2d5baba2831340accbc254``` the compiler doesn't work as well as in the first v2.3.22 commit. In fact, it doesn't work at all in the browser.

I played around with the examples (```examples/live-editor``` being specific) using the latest compiled ```riot+compiler.js```.

The following output was thrown (similar in other riot examples):

```
Error: You must #include brackets before this code!
compile<()
 riot+compiler.js:2851
<anonym>
 riot+compiler.js:2766
<anonym>
 riot+compiler.js:3
 riot+compiler.js:2851:1

ReferenceError: riot is not defined
<anonym>
 index.html:19
 index.html:19:2
```

**Comment by aMarCruz** [comment]
@jrschreiber , sorry by that, I will commit an update.

**Comment by jrschreiber** [comment]
Happy to hear that. Thanks in advance.

Please keep up the great work!

**Comment by jrschreiber** [comment]
Fixed. :)

**Comment by aMarCruz** [comment]
:+1: thanks for your feedback.
