### ISSUE TITLE
adding to `_modnames`

### ISSUE THREAD

**Issue by btakita** [riot/compiler#50]
i'd like to add `ecmascript-6` to `_modnames` & point it to `babel`.

my editor (rubymine/webstorm) seems to require

`<script type="text/ecmascript-6">`

to recognize es6 in script tags

when i add the `type`, i get a build error:

`Module build failed: Error: JS parser not found: "ecmascript-6"`

**Comment by btakita** [comment]
`<script type="text/babel">` fixes the issue that i have.

i can see the utility for people writing plugins to be able to add types though.

**Comment by aMarCruz** [comment]
@btakita : you can do that.
 http://riotjs.com/api/compiler/#js-parser

to use an alias:
`riot.parsers.js['ecmascript-6'] = riot.parsers.js.babel`
and now you can use `<script type="text/ecmascript-6">`

Closing the issue.
