### ISSUE TITLE
ES6 method definitions on the tag fails with babel preprocessor - SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by talee** [riot/compiler#55]
Riot supports "smart ES6 like method syntax" for custom tags per http://riotjs.com/guide/#tag-syntax and this holds true for normal compiles. However when compiled with the babel preprocessor a SyntaxError is generated.

I've created a simple test case here: https://github.com/talee/riot-preset-babel-test

Embedded below for ease of reading (simplified):

    <component>
      ....HTML tags etc.

      <script type="babel">
        // This doesn't work
        sadMethod() {
          return 'T _ T'
        }
    
        // This works
        this.verboseMethod = function() {
          return '- _ -'
        }
      </script>
    </component>

Running ./build.sh or `riot --type babel component.tag` generates:

    SyntaxError: .../riot-preset-babel-test/component.tag: Unexpected token (9:16)

The line numbers are inaccurate (bug?) since they start from the JS source code instead of the top of the file.  9:16 points to the space after the parentheses:

    sadMethod() {
               ^points to here

Global riot and babel settings:

    riot-cli:      2.3.14 - https://github.com/riot/cli
    riot-compiler: 2.3.22 - https://github.com/riot/compiler

    6.5.1 (babel-core 6.5.1)

Let me know if there is any additional info you need to help repro this. Thanks!

**Comment by GianlucaGuarini** [comment]
@talee you can't use both the preprocessors (riot and babel) together. Your javascript gets processed only once either by babel or riot, combining both it's not possible (and it's dangerous). This does not mean that you can not build your own adding special plugin to parse that kind of expressions

**Comment by talee** [comment]
@GianlucaGuarini - Thanks for the explanation! Does the Riot preprocessor do anything else besides transpile ES6 method definitions for tag instances? It would be good to know if there any other situations where I should not use Riot specific syntax.

Running `riot --type babel component.tag` is not clear to the user that the Riot preprocessor is being executed. If mixing Riot and Babel preprocessors is illegal/indeterminate, we should suppress the Riot preprocessor when a `--type` option is passed.

A bonus would be to document this so people using ES6 and following Riot syntax for custom tags aren't confused: http://riotjs.com/guide/compiler/#pre-processors.

**Comment by aMarCruz** [comment]
@talee, the default [riot parser](https://github.com/riot/compiler/blob/master/src/core.js#L398) does nothing more than remove comments and transpile ES6 method definitions.

As @GianlucaGuarini said, you can use only one JS parser, no one example shows method shortcuts of the riot parser with babel.

**Comment by aMarCruz** [comment]
Closing this issue, the answer is clear.
