### ISSUE TITLE
What about ignoring <script> unknown types?

### ISSUE THREAD

**Issue by wellguimaraes** [riot/compiler#57]
I use Webstorm, and it deals nice with es6 syntax when I set the type as "text/ecmascript-6" or "text/babel", but these types are not recognized by Riot compiler and it crashes. Then I have to remove the type attribute before compiling. When the tags are compiled, then I can easily transpile them using the latest version of Babel.

The script parser option could be defined in specific attribute like "parser" instead of "type", OR the compiler could just ignore "unknown" types and work like it was vanilla js.

**Comment by aMarCruz** [comment]
@wellguimaraes I guess you are using babel v6.x, so If the "text/babel" type breaks your code, then you found a bug! The remotion of "text/" [occurs here](https://github.com/riot/compiler/blob/master/lib/compiler.js#L710). Anyway I will check this asap.

Regarding the type "text/ecmascript-6" you can define a new type if you wish. In the browser:
```js
riot.parsers.js['ecmascript-6'] = riot.parsers.js.babel
```
You can do that in the cli as well. Right now I can remember how, please read the cli docs.

**Comment by GianlucaGuarini** [comment]
@wellguimaraes you can define all the parsers you want using the `riot-cli` http://riotjs.com/guide/compiler/#es6-config-file

**Comment by wellguimaraes** [comment]
Sorry, I overlooked. Thank you, one more time.
