### ISSUE TITLE
Failure with cryptic error message when preprocessor module is not installed

### ISSUE THREAD

**Issue by joepie91** [riot/compiler#60]
Possibly related to #17, but not quite the same.

In my Gulp + Webpack + RiotJS setup, I forgot to install the `jade` module, and as a result I got the following error:

```
Error: ./src/components/app.tag
Module build failed: TypeError: (intermediate value)(intermediate value) is not a function
    at _loadParser (/home/sven/projects/riot-todo/node_modules/riot-compiler/lib/parsers.js:55:39)
    at compileTemplate (/home/sven/projects/riot-todo/node_modules/riot-compiler/lib/compiler.js:812:10)
    at Object.compile (/home/sven/projects/riot-todo/node_modules/riot-compiler/lib/compiler.js:881:11)
    at Object.module.exports (/home/sven/projects/riot-todo/node_modules/riotjs-loader/index.js:30:17)
 @ ./src/index.js 3:0-31
```

The responsible configuration was:

```javascript
gulp.task('webpack', function(){
	return gulp.src("./src/index.js")
		// ...
		.pipe(webpackStream({
			watch: true,
			module: {
				preLoaders: [{ test: /\.tag$/, loader: "riotjs-loader", exclude: /node_modules/, query: { type: "babel", template: "jade" } }],
				loaders: [
					// ...
				]
			},
			plugins: [ new webpack.ProvidePlugin({riot: "riot"}) ],
			resolve: {
				// ...
			},
			debug: true
		}))
		// ...
});
```

Installing `jade` resolved the issue. Now, this probably *should* have thrown a human-readable error, due to [this statement](https://github.com/riot/compiler/blob/master/lib/compiler.js#L809-L811) - but presumably due to the addition of the `_loadParser` wrapper function, this statement will never trigger (since `parser` is never falsy), and you end up with the above cryptic error instead.

**Comment by aMarCruz** [comment]
The parsers._req function was rewritten and hope solves this and other issues.
Now it is used by the compiler to load parsers and throws with consistent messages.
