### ISSUE TITLE
When LESS parser fails, only says "unrecognised input"

### ISSUE THREAD

**Issue by dz902** [riot/compiler#62]
Error: Unrecognised input

This is the only message thrown when LESS parser fails, which is not descriptive. 

Even worse is when using Riot with other runners like Webpack, this error message does not even mention it was about LESS. I would suggest when throwing / relaying exceptions from parsers, wrap it with a new exception that belongs to Riot, and indicate the source of error.

**Comment by aMarCruz** [comment]
As a generic tool, the compiler is not wrapping anything, this is the raw exception thrown by less. I think the various tools have to handle this issues based in the context.

Closing this issue now.
