### ISSUE TITLE
Support for "import" inside of tag

### ISSUE THREAD

**Issue by kuashe** [riot/compiler#69]
ES 2015 "import" is not usable at the moment with riot .

Taken from this [issue](https://github.com/riot/riot/issues/1715) 
```
<tag>
   <script>
     import baz from './baz'
     this.foo = 'bar'
   </script>
</tag>
```

```
riot.tag2('tag','', function(opts) {
   import baz from './baz' // import here is not allowed
   this.foo = 'bar'
})
```

I think the compiler needs to translate the import statement into a regular "import" . 

```
import baz from './baz' // Will work this way
riot.tag2('tag','', function(opts) {
   this.foo = 'bar'
})
```

I will try to make thoses changes to the compiler .

**Comment by GianlucaGuarini** [comment]
fixed in riot-compiler@2.5.0
