### ISSUE TITLE
fix the compiler bundle for riot

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/compiler#72]
@aMarCruz with the latest compiler version 2.5.* it seems that the riot.compiler.js bundle does not work properly in riot. Steps to reproduce the issue:

- pull the riot repo
- run npm install riot-compiler
- run make riot

could you please fix this issue? I made a patch 2.5.1 but there are still javascript errors coming from the compiler.

**Comment by aMarCruz** [comment]
Ok

**Comment by aMarCruz** [comment]
@GianlucaGuarini , yeah it was a silly error. Fixed in my last commit.

**Comment by GianlucaGuarini** [comment]
cool thanks @aMarCruz have you already published it on npm?

**Comment by aMarCruz** [comment]
@GianlucaGuarini , no.

**Comment by GianlucaGuarini** [comment]
Ok I will do asap and publish riot@2.5.0
