### ISSUE TITLE
No package in bower.

### ISSUE THREAD

**Issue by M-O-Z-G** [riot/compiler#74]
Hello,

In the description you wrote about installation through the Bower. But this package isn't in Bower.

```
bower ENOTFOUND     Package riot-compiler not found
```
![](https://i.imgur.com/scCdH4e.png)

**Comment by cognitom** [comment]
Right, Bower is mentioned in README.md.
https://github.com/riot/compiler#bower

But I thought that `riot-compiler` was designed to work on Node.js. I'm not sure there's the use case with Bower. How about simply removing the description about Bower on README.md?

**Comment by M-O-Z-G** [comment]
> was designed to work on Node.js

On the contrary, compiler works on client-side instead server. But i was  a little wrong - Riot Bower package come with riot+compiler out-of-the-box, but by default injected only Riot.

bower_components\riot\bower.json:50

**Comment by aMarCruz** [comment]
mmm... brower.json is pointing to `lib/compiler.js` and this is the wrong place. I will correct it asap.

**Comment by cognitom** [comment]
Oh, it supposed be `dist/riot.compiler.js`.

@M-O-Z-G yeah, though the compiler itself works on browser, most of users may access it via `riot+compiler.js`. But it'll be also fine if `riot-compiler` is provided from Bower, too.

I'm thinking about progressive web apps with service workers. Then it makes sense that the separated version of `riot-compiler` may be needed on the browser. Not yet tried.

**Comment by aMarCruz** [comment]
@cognitom you're right, however riot-compiler.js was deigned to be part of riot and needs some touch to work standalone.

**Comment by GianlucaGuarini** [comment]
I think making the compiler standalone fro the browser is useless. The bower release is makes no sense. I would prefere the focus on the sourcemaps instead

**Comment by cognitom** [comment]
If it needs some touch, Bower support has no priority. Source maps :+1:

**Comment by GianlucaGuarini** [comment]
My patch removes bower from this repo because it does not make any sense
