### ISSUE TITLE
Move function declarations to the top?

### ISSUE THREAD

**Issue by rogueg** [riot/compiler#78]
I often find myself writing code like this:

```
<my-tag>
  this.updateResult()

  updateResult() {
    // some expensive calculation
  }
</my-tag>
```

This would work if it was normal JS, but because riot rewrites function declarations, it throws an `updateResult is not a function`. What if the above code was translated to this:

```
this.updateResult = (function() {...}).bind(this)

// == user's constructor code goes here
this.updateResult()
```

This lets users keep all their constructor code at the top, which makes things more readable (especially if you have lots of functions).

**Comment by andyfleming** [comment]
If it's not too much of a pain, I'd agree that this should be consistent with javascript's normal hoisting behavior.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function#Function_declaration_hoisting

**Comment by cognitom** [comment]
Looks easy to change it. Just inserting the function on top, instead of bottom of `parts`
https://github.com/riot/compiler/blob/v2.5.3/lib/compiler.js#L413-L426

**Comment by aMarCruz** [comment]
@cognitom you're right, It looks easy, this week...

**Comment by aMarCruz** [comment]
btw, I was thinking the other day about the functions generated by the `riotjs` parser, ex. from:
```js
func(){ blah }
```
to
```js
this.func = function() { blah }.bind(this)
```

Is `bind` neccesary in this case?

So it was in the original compiler so I kept it, but it seems redundant. In my code I've never had a need for `bind` with functions declared that way as they are always called with the correct context.

@cognitom , @rogueg , If I'm not missing something maybe we can remove the `bind` in tmpl v3.

**Comment by rogueg** [comment]
I don't know much about the compiler changes, but I think it was (is?) useful in this case:
```
<my-tag>
  <div each={x in items}>
    <p>{getCount()}</p>
  </div>
  
  this.count = 0

  getCount() {
    this.count += 1
    return this.count
  }
</my-tag>
```

`getCount` gets called against the anonymous tag created by `each`. Without the bind, we'd update `count` on that anonymous tag, rather than my-tag.

**Comment by aMarCruz** [comment]
@rogueg I see now, thanks.

**Comment by GianlucaGuarini** [comment]
closing this issue as clear [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle) violation. The riot compiler will convert your components avoiding to touch your original javascript, if you need any special js preprocessor you can rely on `registerPreprocessor` method
