### ISSUE TITLE
Remove bool attrs '__'

### ISSUE THREAD

**Issue by limodou** [riot/compiler#85]
I'm using riot 3.0.0alpha10，but the compiler will still output `__` for bool attributes, so which version will fix this?

**Comment by GianlucaGuarini** [comment]
How do you compiler your tags?

**Comment by limodou** [comment]
I install riot-compiler via npm, and run `riot mytag.tag` in command line. I found the newest version of riot-compiler is 2.5.5.

**Comment by GianlucaGuarini** [comment]
Well if you want to use the new compiler you need to use the version `^3.0.0-alpha.1` https://github.com/riot/riot/blob/1113a888f442002c58ac268cef2e49b739458ed7/package.json#L49 this problem was already fixed and I am closing issue. Thanks anyway
