### ISSUE TITLE
Riot compiler behavior on compiling method

### ISSUE THREAD

**Issue by vojtabiberle** [riot/compiler#90]
1. Describe your issue:
When I place `{` opening bracket  of method on new line in `<script>` tag, Riot compiler don't build my method correctly.

2. Can you reproduce the issue?
```
<my-tag>
  <h1>{ message }</h1>
  <button onclick={ handleClick }>Button 1</button>
  <button onclick={ handleClickBad }>Button 2</button>

  <script>
    this.message = 'hello there'
    
    handleClick(e) {
      this.message = 'Click';
    }
    
    handleClickBad(e)
    {
      this.message = 'Click bad';
    }
    
  </script>
</my-tag>
```

becomes this
```
riot.tag('my-tag', '<h1>{ message }</h1><button onclick={ handleClick }>Button 1</button><button onclick={ handleClickBad }>Button 2</button>', function(opts){
  this.message = 'hello there'
    
    this.handleClick = function(e) {
      this.message = 'Click';
    }.bind(this);
    
    handleClickBad(e)
    {
      this.message = 'Click bad';
    }
}));
```

  - [Riot compiler behavior on compiling method](http://plnkr.co/edit/yuMTpWRvJPDvXtvH28uO)

3. On which browser/OS does the issue appear?
Ubuntu 16.04

4. Which version of Riot does it affect?
Riot 2.6.7 compiled with grunt-riot

5. How would you tag this issue?

  - [ ] Question
  - [x] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

Moved from [riot/riot/issues/2065](https://github.com/riot/riot/issues/2065)

**Comment by GianlucaGuarini** [comment]
This is not a riot-compiler issue https://runkit.com/gianlucaguarini/riot-compiler-rendering-test
gruint-riot uses an old riot release I recommend to open the issue directly on grunt-riot or just to use the official riot compiler/cli

**Comment by vojtabiberle** [comment]
Thanks for response
