### ISSUE TITLE
New import regex matches incorrectly

### ISSUE THREAD

**Issue by imagentleman** [riot/compiler#91]
The recent regex change on version 2.5.6 in this line:

https://github.com/riot/compiler/blob/master/src/core.js#L133

Matches text incorrectly. It matches from the word "import" to the last single or double quote on the entire tag, not to the end of the import.

Example:

https://regex101.com/r/Isww62/1

Previous regex behavior:

https://regex101.com/r/Isww62/2

This problem breaks any tag with ES6 imports inside.

**Comment by believer-ufa** [comment]
Yes, please please, fix this issue. All my tags now compiles incorrectly)

**Comment by imagentleman** [comment]
Just sent a pr that may fix this.

In the meantime, i think there are several workarounds:

1. Add riot-compiler version 2.5.5 (the exact version, not ^2.5.5) on your own project's package.json dependencies. Version 2.5.5 doesn't have the issue introduced on the latest version (2.5.6).

2. Use requires instead of imports.

3. Put the imports outside of the tag (at the top before the html begins).

Hopefully there is a long term fix soon that doesn't require code changes.

**Comment by GianlucaGuarini** [comment]
@imagentleman thank you so much https://github.com/riot/compiler/releases/tag/v2.5.7
