### ISSUE TITLE
Support for unscoped css?

### ISSUE THREAD

**Issue by btakita** [riot/compiler#93]
As of v3, is there any way to have unscoped css in the tags?

**Comment by cognitom** [comment]
@btakita I think there's no option to turn it off.
https://github.com/riot/compiler/blob/v3.0.0/src/core.js#L594

How about adding CSS file directly into HTML...?

**Comment by btakita** [comment]
Thank you, I ended up doing just that with a sass build; rolling my own build system with bash scripts * json files.

Sometimes it's nice to have elements act as state machines to the child elements, using css classes.

parent-component.tag
```
<parent-component id="parent" class="{state1: ctx.state1, state2: ctx.state2}">
  <child-component>
  </child-component>
</parent-component>
```

child-component.tag
```
<child-component>
  <section class="state1"></section>
  <section class="state2"></section>
</child-component>
```

child-component.css
```
child-component {
  display: block;
  visibility: hidden;
}
.state1 child-component .state1 {
  visibility: visible;
}
.state2 child-component .state2 {
  visibility: visible;
}
```
