### ISSUE TITLE
using css variables with compiler 3.0.0

### ISSUE THREAD

**Issue by jsannerstedt** [riot/compiler#95]
I compile my css like so

`riot src/common/tags temp/tags.css --export css`

and later on I use postcss to modify temp/tags.css

in my main tag I set up som css variables

`:root {
  --primary-text: #050505;
  --shadow-element: {
    box-shadow: 2px 2px 3px 0 rgba(0, 0, 0, .2);
  };
  --shadow-element-darker: {
    box-shadow: 2px 2px 3px 0 rgba(0, 0, 0, .35);
  };
  --shadow-element-framed: {
    box-shadow: 2px 2px 3px 1px rgba(0, 0, 0, .3);
  };
}`

In older versions this would just be output as is. With riot compiler 3.0.0, instead I get

`:root {
  my-tag-name --primary-text: #050505;
  --shadow-element:, [ data-is = "my-tag-name" ]
  --primary-text: #050505;
  --shadow-element: {
    box-shadow: 2px 2px 3px 0 rgba(0, 0, 0, .2);
  } my-tag-name --shadow-element-darker:, [ data-is = "my-tag-name" ] --shadow-element-darker: {
  box-shadow: 2px 2px 3px 0 rgba(0, 0, 0, .35);
} my-tag-name --shadow-element-framed:, [ data-is = "my-tag-name" ] --shadow-element-framed: {
  box-shadow: 2px 2px 3px 1px rgba(0, 0, 0, .3);
};
}`

this is obviously not valid and thus, postcss fails... 

any ideas what I can do?

**Comment by cognitom** [comment]
@jsannerstedt In riot 3 all the css will be scoped by default. But Riot's style parser doesn't support css variable at this point. So we need to `postcss` before passing it.
http://riotjs.com/guide/migration-from-riot2/#scoped-css-by-default

We could set custom parser in [the config file](http://riotjs.com/guide/compiler/#es6-config-file), I think.
(Anyway we need some example. I'll try to make one for [Riot Examples](https://github.com/riot/examples) later...)

**Comment by GianlucaGuarini** [comment]
@jsannerstedt note that you have used `:root` and riot does not support shadowdom yet. You need to use `:scope` instead and unfortunally you can not use css vars yet

**Comment by jsannerstedt** [comment]
fair enough. just unfortunate that it worked earlier, but not now... anywho, I'll try some workaround, keep up the good work :)

**Comment by GianlucaGuarini** [comment]
Before you were assigning `:root` but you were referring to the document root and not the component root so it was wrong anyway

**Comment by cognitom** [comment]
@jsannerstedt I've sent a PR to Riot Examples right now. https://github.com/riot/examples/pull/49

You can check it here temporally:
https://github.com/riot/examples/tree/riot-config/riot-config
*Note*: this branch will be deleted after merging.

I had to do a small hack on it. postcss doesn't understand `:scope` selector, so I simply replace `:scope` to `:root` and replace it back after process by postcss:
https://github.com/riot/examples/blob/riot-config/riot-config/riot.config.js#L13-L15

**Comment by GianlucaGuarini** [comment]
The new riot v4.0.0 compiler supports perfectly css variables out of the box http://plnkr.co/edit/gE6T5Bu33x4LAYTpESRs?p=preview
